from . import auth
from . import favorites
from . import history
from . import dashboard
from . import recommendations
from . import movies
from . import watchlist
from . import reviews
from . import profile